title: Portfolio of Jonathan Forrider
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6772288
  brandStrength: 0.8878695489838719
  lightness: 0.8501611
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.6020408
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74192809-1
  facebook: null
favicon: null
name: jonathan.forrider
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8555317
layout_spectrum: 0.1863587
