name: jonathan.forrider
favicon: null
layout_spectrum: 0.94843
typography_spectrum: 0.38165116077288985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8878695489838719
  lightness: 0.029918248765170574
  saturation: 0.7423222821671516
  rhythmicContrast: 0.2311202057171613
purpose: []
