layout_spectrum: 0.538837890778991
typography_spectrum: 0.1636606173247726
color:
  saturation: 0.3183679347552617
  brandStrength: 0.09587668812759959
  lightness: 0.4742943959931225
  brandColors:
    - '#FFFFFF'
    - '#8A7153'
    - '#5E4A3F'
    - '#E1C8A9'
    - '#8F7AF1'
  rhythmicContrast: 0.2077564199823923
title: Through the Eyes of a Programmer
purpose:
  - type: external
    url: 'https://github.com/jd4rider'
    label: Github
  - type: external
    url: 'http://jfwebdesigns.altervista.org/'
    label: JF Web Designs
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74192809-1
  facebook: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8bc7540d-d58d-4de4-905c-f8b22f90fced.jpg
name: jonathan.forrider
opengraph:
  image: null
  type: null
  appId: null
content: []
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8c6e3943-093a-4632-9aa1-d1af0ffa9da2.jpg
author:
  name: Jonathan David Forrider
  email: jd4rider@gmail.com
description: Portfolio of Jonathan Forrider
